import {
  BarChart3,
  Binary,
  BookOpen,
  BrainCircuit,
  CalendarCheck,
  CircuitBoard,
  Code2,
  Database,
  FileCode2,
  Gauge,
  GraduationCap,
  Home,
  Network,
  Rocket,
  ServerCog,
  Sigma,
  TimerReset,
} from "lucide-react";
import type {
  Difficulty,
  RevisionItem,
  StudyTask,
  Subject,
  Topic,
  WeeklyGoal,
} from "@/types/study";

export const GATE_2027_DATE = new Date("2027-02-07T00:00:00+05:30");

export const navItems = [
  { title: "Dashboard", href: "/dashboard", icon: Home },
  { title: "Study Engine", href: "/study", icon: CalendarCheck },
  { title: "Subjects", href: "/subjects", icon: BookOpen },
  { title: "Placement", href: "/placement", icon: Code2 },
  { title: "AI Mentor", href: "/mentor", icon: BrainCircuit },
  { title: "Analytics", href: "/analytics", icon: BarChart3 },
];

const topic = (
  subjectId: string,
  id: string,
  name: string,
  subtopics: string[],
  progress: number,
  difficulty: Difficulty,
  estimatedHours: number,
  weightage = "Medium",
): Topic => ({
  id,
  subjectId,
  name,
  subtopics,
  progress,
  difficulty,
  estimatedHours,
  weightage,
  notes: [
    `Build one-page notes for ${name} with definitions, corner cases, and common traps.`,
    "Add one worked example for every recurring GATE pattern.",
  ],
  formulas: [
    "Maintain derivations separately from final formulas.",
    "Tag formulas as direct, derived, or conceptual.",
  ],
  pyqs: [
    "Solve latest 10 GATE CS PYQs topic-wise.",
    "Reattempt incorrect PYQs after 3 and 10 days.",
  ],
  resources: [
    "GATE Overflow discussions",
    "NPTEL lectures",
    "Standard textbook chapter notes",
  ],
  revisionChecklist: {
    first: progress >= 35,
    second: progress >= 60,
    third: progress >= 85,
  },
});

export const gateSubjects = [
  {
    id: "engineering-mathematics",
    name: "Engineering Mathematics",
    icon: Sigma,
    progress: 42,
    weightage: "13-15 marks",
    difficulty: "Medium",
    estimatedHours: 92,
    topics: [
      topic("engineering-mathematics", "linear-algebra", "Linear Algebra", ["Matrices", "Eigenvalues", "Rank", "Vector spaces"], 55, "Medium", 18, "High"),
      topic("engineering-mathematics", "calculus", "Calculus", ["Limits", "Continuity", "Differentiability", "Maxima and minima"], 38, "Medium", 16),
      topic("engineering-mathematics", "probability", "Probability", ["Random variables", "Distributions", "Expectation", "Bayes theorem"], 31, "Hard", 18, "High"),
      topic("engineering-mathematics", "discrete-math", "Discrete Mathematics", ["Logic", "Combinatorics", "Recurrence", "Graph basics"], 44, "Medium", 20),
    ],
  },
  {
    id: "data-structures",
    name: "Data Structures",
    icon: Binary,
    progress: 58,
    weightage: "8-10 marks",
    difficulty: "Medium",
    estimatedHours: 70,
    topics: [
      topic("data-structures", "arrays-strings", "Arrays and Strings", ["Prefix sums", "Two pointers", "Sliding window", "String matching"], 72, "Easy", 10),
      topic("data-structures", "trees", "Trees", ["BST", "AVL", "Heap", "Traversals"], 60, "Medium", 16, "High"),
      topic("data-structures", "graphs", "Graphs", ["Representation", "BFS", "DFS", "Topological sort"], 42, "Hard", 18, "High"),
      topic("data-structures", "hashing", "Hashing", ["Collision handling", "Load factor", "Open addressing", "Chaining"], 58, "Medium", 10),
    ],
  },
  {
    id: "algorithms",
    name: "Algorithms",
    icon: Gauge,
    progress: 35,
    weightage: "8-12 marks",
    difficulty: "Hard",
    estimatedHours: 96,
    topics: [
      topic("algorithms", "analysis", "Asymptotic Analysis", ["Big-O", "Recurrences", "Master theorem", "Amortized analysis"], 52, "Medium", 14),
      topic("algorithms", "greedy", "Greedy Algorithms", ["Exchange argument", "Activity selection", "MST", "Huffman coding"], 38, "Hard", 18),
      topic("algorithms", "dynamic-programming", "Dynamic Programming", ["State design", "Knapsack", "LCS", "Matrix chain"], 24, "Hard", 24, "High"),
      topic("algorithms", "graph-algorithms", "Graph Algorithms", ["Shortest path", "MST", "SCC", "Max flow basics"], 29, "Hard", 22, "High"),
    ],
  },
  {
    id: "dbms",
    name: "DBMS",
    icon: Database,
    progress: 61,
    weightage: "7-9 marks",
    difficulty: "Medium",
    estimatedHours: 72,
    topics: [
      topic("dbms", "er-model", "ER Model", ["Entity sets", "Relationships", "Cardinality", "Weak entities"], 78, "Easy", 8),
      topic("dbms", "sql", "SQL", ["Joins", "Aggregation", "Nested queries", "Relational algebra"], 62, "Medium", 14, "High"),
      topic("dbms", "normalization", "Normalization", ["FDs", "Closures", "BCNF", "3NF decomposition"], 55, "Hard", 16, "High"),
      topic("dbms", "transactions", "Transactions", ["Serializability", "Recoverability", "Locking", "Deadlocks"], 49, "Hard", 18),
    ],
  },
  {
    id: "operating-systems",
    name: "Operating Systems",
    icon: ServerCog,
    progress: 47,
    weightage: "7-10 marks",
    difficulty: "Hard",
    estimatedHours: 88,
    topics: [
      topic("operating-systems", "processes", "Processes and Threads", ["PCB", "Context switch", "IPC", "Threads"], 58, "Medium", 14),
      topic("operating-systems", "scheduling", "CPU Scheduling", ["FCFS", "SJF", "Round robin", "Priority scheduling"], 64, "Medium", 12, "High"),
      topic("operating-systems", "memory", "Memory Management", ["Paging", "Segmentation", "TLB", "Page replacement"], 38, "Hard", 20, "High"),
      topic("operating-systems", "file-systems", "File Systems", ["Allocation", "Inodes", "Disk scheduling", "RAID"], 28, "Hard", 14),
    ],
  },
  {
    id: "computer-networks",
    name: "Computer Networks",
    icon: Network,
    progress: 29,
    weightage: "7-9 marks",
    difficulty: "Medium",
    estimatedHours: 84,
    topics: [
      topic("computer-networks", "network-models", "Network Models", ["OSI", "TCP/IP", "Encapsulation", "Services"], 44, "Easy", 8),
      topic("computer-networks", "transport-layer", "Transport Layer", ["TCP", "UDP", "Flow control", "Congestion control"], 22, "Hard", 18, "High"),
      topic("computer-networks", "network-layer", "Network Layer", ["IP", "Subnetting", "Routing", "ICMP"], 31, "Medium", 18, "High"),
      topic("computer-networks", "application-layer", "Application Layer", ["DNS", "HTTP", "Email", "Sockets"], 18, "Medium", 10),
    ],
  },
  {
    id: "computer-organization",
    name: "Computer Organization",
    icon: CircuitBoard,
    progress: 26,
    weightage: "6-8 marks",
    difficulty: "Hard",
    estimatedHours: 86,
    topics: [
      topic("computer-organization", "instructions", "Instruction Set Architecture", ["Addressing modes", "Instructions", "ALU", "Control unit"], 34, "Medium", 16),
      topic("computer-organization", "pipelining", "Pipelining", ["Hazards", "Speedup", "Forwarding", "Branching"], 22, "Hard", 18, "High"),
      topic("computer-organization", "memory-hierarchy", "Memory Hierarchy", ["Cache", "Mapping", "Replacement", "Virtual memory"], 25, "Hard", 20, "High"),
      topic("computer-organization", "io", "I/O Organization", ["Interrupts", "DMA", "Buses", "Polling"], 20, "Medium", 10),
    ],
  },
  {
    id: "digital-logic",
    name: "Digital Logic",
    icon: Binary,
    progress: 68,
    weightage: "5-7 marks",
    difficulty: "Easy",
    estimatedHours: 52,
    topics: [
      topic("digital-logic", "boolean-algebra", "Boolean Algebra", ["Laws", "Duality", "Canonical forms", "Simplification"], 78, "Easy", 8),
      topic("digital-logic", "k-maps", "K-Maps", ["SOP", "POS", "Don't cares", "Prime implicants"], 74, "Easy", 8),
      topic("digital-logic", "combinational", "Combinational Circuits", ["Adders", "MUX", "Decoder", "Comparator"], 62, "Medium", 12),
      topic("digital-logic", "sequential", "Sequential Circuits", ["Flip-flops", "Counters", "Registers", "FSM"], 54, "Medium", 14),
    ],
  },
  {
    id: "theory-of-computation",
    name: "Theory of Computation",
    icon: FileCode2,
    progress: 31,
    weightage: "7-9 marks",
    difficulty: "Hard",
    estimatedHours: 90,
    topics: [
      topic("theory-of-computation", "regular-languages", "Regular Languages", ["DFA", "NFA", "Regex", "Pumping lemma"], 42, "Medium", 18, "High"),
      topic("theory-of-computation", "context-free", "Context Free Languages", ["CFG", "CNF", "Parse trees", "Ambiguity"], 28, "Hard", 20),
      topic("theory-of-computation", "pda", "Pushdown Automata", ["Stack behavior", "Acceptance", "DPDA", "NPDA"], 22, "Hard", 14),
      topic("theory-of-computation", "turing-machines", "Turing Machines", ["Decidability", "Reducibility", "RE languages", "Halting"], 18, "Hard", 16, "High"),
    ],
  },
  {
    id: "compiler-design",
    name: "Compiler Design",
    icon: FileCode2,
    progress: 18,
    weightage: "4-6 marks",
    difficulty: "Hard",
    estimatedHours: 62,
    topics: [
      topic("compiler-design", "lexical-analysis", "Lexical Analysis", ["Tokens", "Regex", "DFA construction", "Lex"], 28, "Medium", 10),
      topic("compiler-design", "parsing", "Parsing", ["LL(1)", "LR", "FIRST/FOLLOW", "Parse tables"], 16, "Hard", 18, "High"),
      topic("compiler-design", "syntax-directed", "Syntax Directed Translation", ["Attributes", "SDD", "Type checking", "Intermediate code"], 14, "Hard", 14),
      topic("compiler-design", "code-generation", "Code Generation", ["Basic blocks", "DAG", "Optimization", "Register allocation"], 10, "Hard", 12),
    ],
  },
  {
    id: "general-aptitude",
    name: "General Aptitude",
    icon: GraduationCap,
    progress: 53,
    weightage: "15 marks",
    difficulty: "Easy",
    estimatedHours: 48,
    topics: [
      topic("general-aptitude", "verbal", "Verbal Ability", ["Grammar", "Sentence completion", "Reading", "Vocabulary"], 61, "Easy", 10),
      topic("general-aptitude", "quantitative", "Quantitative Aptitude", ["Percentages", "Ratios", "Time-work", "Speed-distance"], 48, "Medium", 14, "High"),
      topic("general-aptitude", "reasoning", "Reasoning", ["Arrangements", "Logic", "Series", "Puzzles"], 55, "Easy", 10),
      topic("general-aptitude", "data-interpretation", "Data Interpretation", ["Tables", "Charts", "Averages", "Approximation"], 44, "Medium", 10),
    ],
  },
] satisfies Array<Subject & { icon: typeof Sigma }>;

export const placementSubjects = [
  "DSA",
  "OOP",
  "DBMS",
  "OS",
  "CN",
  "SQL",
  "System Design",
  "HR Interview",
];

export const todayTasks: StudyTask[] = [
  {
    id: "task-1",
    title: "First revision: DBMS normalization",
    subject: "DBMS",
    subjectId: "dbms",
    topicId: "normalization",
    mode: "revision",
    revisionStage: "first",
    dueDate: "2026-06-11",
    minutes: 45,
    priority: "High",
    status: "pending",
    generatedReason: "High weightage topic with incomplete first revision.",
  },
  {
    id: "task-2",
    title: "Graph algorithms PYQ block",
    subject: "Algorithms",
    subjectId: "algorithms",
    topicId: "graph-algorithms",
    mode: "practice",
    dueDate: "2026-06-11",
    minutes: 70,
    priority: "High",
    status: "pending",
    generatedReason: "Weak progress and high placement overlap.",
  },
  {
    id: "task-3",
    title: "OS scheduling timed drill",
    subject: "Operating Systems",
    subjectId: "operating-systems",
    topicId: "scheduling",
    mode: "practice",
    dueDate: "2026-06-11",
    minutes: 35,
    priority: "Medium",
    status: "completed",
    generatedReason: "Recently learned topic due for active recall.",
  },
  {
    id: "task-4",
    title: "CN transport layer concept map",
    subject: "Computer Networks",
    subjectId: "computer-networks",
    topicId: "transport-layer",
    mode: "learn",
    dueDate: "2026-06-11",
    minutes: 50,
    priority: "High",
    status: "pending",
    generatedReason: "Low completion and upcoming weekly goal.",
  },
  {
    id: "task-5",
    title: "Placement DSA: 2 easy, 2 medium, 1 hard",
    subject: "DSA",
    mode: "placement",
    dueDate: "2026-06-11",
    minutes: 90,
    priority: "High",
    status: "pending",
    generatedReason: "Daily placement baseline.",
  },
];

export const revisionQueue: RevisionItem[] = [
  {
    id: "rev-1",
    topic: "Normalization",
    subject: "DBMS",
    stage: "first",
    dueDate: "Today",
    status: "pending",
    spacingDays: 1,
  },
  {
    id: "rev-2",
    topic: "CPU Scheduling",
    subject: "Operating Systems",
    stage: "second",
    dueDate: "Tomorrow",
    status: "pending",
    spacingDays: 3,
  },
  {
    id: "rev-3",
    topic: "K-Maps",
    subject: "Digital Logic",
    stage: "third",
    dueDate: "Jun 15",
    status: "completed",
    spacingDays: 10,
  },
];

export const weeklyGoals: WeeklyGoal[] = [
  { goal: "Finish CN transport layer", target: "4 sessions", progress: 60 },
  { goal: "Complete 3 GATE mocks", target: "1 / 3 done", progress: 33 },
  { goal: "Clear 18 revision cards", target: "11 / 18 done", progress: 61 },
  { goal: "Solve 35 placement DSA problems", target: "19 / 35 done", progress: 54 },
];

export const readinessSignals = [
  { name: "GATE Readiness", value: 46, icon: Rocket },
  { name: "Placement Readiness", value: 39, icon: Code2 },
  { name: "Mock Test Discipline", value: 52, icon: TimerReset },
  { name: "GitHub Project Depth", value: 24, icon: BrainCircuit },
];

export const studyHoursData = [
  { day: "Mon", hours: 3, target: 5 },
  { day: "Tue", hours: 4.5, target: 5 },
  { day: "Wed", hours: 2, target: 5 },
  { day: "Thu", hours: 5, target: 5 },
  { day: "Fri", hours: 4, target: 5 },
  { day: "Sat", hours: 6, target: 5 },
  { day: "Sun", hours: 3.5, target: 5 },
];

export const weeklyPerformanceData = [
  { week: "W1", planned: 28, completed: 19 },
  { week: "W2", planned: 31, completed: 24 },
  { week: "W3", planned: 30, completed: 22 },
  { week: "W4", planned: 34, completed: 28 },
];
